# Autogenerated Alembic migration script

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create initial schema."""
    pass


def downgrade() -> None:
    """Drop initial schema."""
    pass
